version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22.x

  pre_build:
    commands:
      - yarn install
      - yarn install -g typescript

  build:
    commands:
      - cd typescript
      - yarn run build
      - yarn run lint
      - yarn run test