version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22.x
      dotnet: 8.0

  pre_build:
    commands:
      - cd typescript
      - yarn install
      - cd ..

      - cd dotnet
      - dotnet restore
      - cd ..

  build:
    commands:
      - cd typescript
      - yarn run build
      - yarn run lint
      - yarn run test
      - cd ..

      - cd dotnet
      - dotnet build
      - dotnet test
