version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22.x

  pre_build:
    commands:
      - cd typescript
      - yarn install

  build:
    commands:
      - yarn run build
      - yarn run lint
      - yarn run test